version: 0.2

plugins:
  - serverless-apigw-binary
  - serverless-fix-apigw-int
phases:
  pre_build:
    commands:
      - npm install
      - npm install -g @angular/cli
      - npm install serverless --global
      - npm install -g serverless-fix-apigw-int
  build:
    commands:
      - ng build --prod
  post_build:
    commands:
      - export SERVERLESS_ACCESS_KEY=AKODcaD3pubdZywX3b47D13OfjWLdIct59VgJYizD5mHE
      - export AWS_ACCESS_KEY_ID=AKIA3OGPS3XYFWA6YZVY
      - export AWS_SECRET_ACCESS_KEY=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
      - aws configure 
      - AKIA3OGPS3XYFWA6YZVY
      - tR+5yEcZWT7HMqrH+QGM5WtQOk12hpC7iKvXNoBo
      - eu-central-1
      - serverless deploy 
      - printf '{"ImageURI":"image_URI"}' > imageDetail.json
      - aws s3api list-buckets --query "Buckets[].Name"
      - aws s3 sync ./dist/MVP-FRONTEND s3://mvp-beta --acl 'public-read' --delete

artifacts:
  files:
    - imageDetail.json



      
