version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - ng build --prod
  post_build:
    commands:
      - aws s3 sync ./dist/mvp-frontend s3://mvp-beta --acl 'public-read' --delete
      
      
