version: 0.2

phases:
  pre_build:
    commands:
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - ng build --prod
  post_build:
    commands:
      - aws s3api list-buckets --query "Buckets[].Name"
      - aws s3 sync s3://mvp-beta /dist/mvp-frontend --acl 'public-read' --delete

artifacts:
  files:
    - '**/*.html'
    - '**/*.js'
    - '**/*.css'
    - '**/*.ico'
  discard-paths: yes
  base-directory: 'dist/mvp-frontend'
      
      
