version: 0.0
Resources:

- TargetService:

Type: AWS::ECS::Service
phases:
  pre_build:
    commands:
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - ng build --prod
  post_build:
    commands:
      - aws s3api list-buckets --query "Buckets[].Name"



      
