version: 0.2


phases:
  pre_build:
    commands:
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - ng build --prod
  post_build:
    commands:
      - printf '{"ImageURI":"image_URI"}' > imageDetail.json
      - aws s3api list-buckets --query "Buckets[].Name"
      - aws s3 sync ./ s3://codepipeline-eu-central-1-339353960839 --acl 'public-read' --delete

artifacts:
  files:
    - imageDetail.json
    - '**/*.html'
    - '**/*.js'
    - '**/*.css'
    - '**/*.ico'
  discard-paths: yes


      
